---
- hosts: dev
  tasks:
  - name: Clone Project
    git:
      repo: https://github.com/marcosroberto1808/mywebsite-docker.git
      dest: /home/vagrant/deploy


  - name: build container image
        docker_image:
          name: mywebsite-docker-image
          build:
            path: /home/vagrant/deploy
            source: build
          state: present
          
  - name: build container image
      docker_image:
        name: mywebsite-docker-image
        build:
          path: /home/vagrant/deploy
          source: build
        state: present
   
   - name: run container 
    docker:
      name: mywebsite-docker-container
      image: mywebsite-docker-image
      state: started
      expose:
      - 80
      
