---
- hosts: dev
  tasks:
  - name: Clone Project
    git:
      repo: https://github.com/marcosroberto1808/mywebsite-docker.git
      dest: /home/vagrant/deploy
      
  - name: build container image
    docker_image:
      name: mywebsite-docker-image
      path: /home/vagrant/deploy/
      dockerfile: Dockerfile
      state: present
