---
- hosts: dev
  become: true
  tasks:
  - name: Clone Project
    git:
      repo: https://github.com/marcosroberto1808/mywebsite-docker.git
      dest: /home/vagrant/mywebsite-deploy
      
  - name: Install pip3
    apt: name=python3-pip state=present 
      
  - name: Install Docker Module for Python
    pip:
      name: docker
      
  - name: Install Docker Compose Module for Python
    pip:
      name: docker-compose

  - name: Tear down existing services
    docker_compose:
      project_src: /home/vagrant/mywebsite-deploy/
      state: absent

  - name: Create and start services
    docker_compose:
      project_src: /home/vagrant/mywebsite-deploy/
    register: output

  - ansible.builtin.debug:
      var: output

  - name: Run `docker-compose up` again
    docker_compose:
      project_src: /home/vagrant/mywebsite-deploy/
      build: yes
    register: output
